#!/bin/bash

set -eu

if [ "$#" -lt 2 ] || [ "$#" -gt 3 ]; then
    echo "Usage: $0 <windows_ip> <wsl_or_container_ip> [output_xml]" >&2
    exit 1
fi

windows_ip="$1"
wsl_ip="$2"
output_xml="${3:-$(pwd)/fastdds-static-peers.xml}"

cat > "${output_xml}" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
  <transport_descriptors>
    <transport_descriptor>
      <transport_id>UdpTransport</transport_id>
      <type>UDPv4</type>
      <maxInitialPeersRange>32</maxInitialPeersRange>
    </transport_descriptor>
  </transport_descriptors>
  <participant profile_name="udp_static_peers_profile" is_default_profile="true">
    <rtps>
      <userTransports>
        <transport_id>UdpTransport</transport_id>
      </userTransports>
      <useBuiltinTransports>false</useBuiltinTransports>
      <builtin>
        <initialPeersList>
          <locator>
            <udpv4>
              <address>127.0.0.1</address>
            </udpv4>
          </locator>
          <locator>
            <udpv4>
              <address>${windows_ip}</address>
            </udpv4>
          </locator>
          <locator>
            <udpv4>
              <address>${wsl_ip}</address>
            </udpv4>
          </locator>
        </initialPeersList>
      </builtin>
    </rtps>
  </participant>
</profiles>
EOF

echo "Wrote ${output_xml}"
