#!/bin/sh

: "${RMCS_PATH:=/workspaces/RMCS}"

export RMW_IMPLEMENTATION="${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}"
export ROS_DOMAIN_ID="${ROS_DOMAIN_ID:-0}"
export ROS_LOCALHOST_ONLY=0
export ROS_AUTOMATIC_DISCOVERY_RANGE=SUBNET
export RMW_FASTRTPS_USE_QOS_FROM_XML="${RMW_FASTRTPS_USE_QOS_FROM_XML:-1}"
if [ -n "${RMCS_FASTDDS_PROFILE:-}" ]; then
    export FASTDDS_DEFAULT_PROFILES_FILE="${RMCS_FASTDDS_PROFILE}"
else
    export FASTDDS_DEFAULT_PROFILES_FILE="${FASTDDS_DEFAULT_PROFILES_FILE:-${RMCS_PATH}/fastdds.xml}"
fi
export FASTRTPS_DEFAULT_PROFILES_FILE="${FASTRTPS_DEFAULT_PROFILES_FILE:-${FASTDDS_DEFAULT_PROFILES_FILE}}"
